# Generated by Django 4.0.2 on 2022-05-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='job/'),
            preserve_default=False,
        ),
    ]
