# Generated by Django 4.0.2 on 2022-05-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='apply_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='coverLetter',
            field=models.FileField(upload_to='candidate/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(upload_to='candidate/'),
        ),
    ]
